Repository Seoul-NolGoat/be-seoul-nolgoat, pull requests merged in 2025-01, with the labels that each got.

#101 상점의 리뷰가 하나 있을 때 삭제되지 않는 오류 해결
  src/main/java/wad/seoul_nolgoat/domain/store/Store.java
Labels: 🐞 Fix

#104 MDC 필터의 잘못된 형변환 로직 수정
  src/main/java/wad/seoul_nolgoat/filter/MDCFilter.java
Labels: 🐞 Fix

#106 CI/CD 적용
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#109 배포 스크립트에 파일 권한 설정 추가
  .github/workflows/deploy.yml
Labels: 🐞 Fix, 🌏 Deploy

#111 배포 스크립트 누락된 설정 추가
  .github/workflows/deploy.yml
Labels: 🐞 Fix, 🌏 Deploy

#116 배포 스크립트 누락된 백그라운드 실행 설정 추가
  .github/workflows/deploy.yml
Labels: 🐞 Fix, 🌏 Deploy

#117 [Release] 1차 배포 - 누락된 백그라운드 실행 설정 추가
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#119 무한 대기 문제 해결을 위한 배포 스크립트 수정
  .github/workflows/deploy.yml
Labels: 🐞 Fix, 🌏 Deploy

#120 [Release] 1차 배포 - EC2 무한 대기 문제 해결
  .github/workflows/deploy.yml
Labels: 🌏 Deploy

#123 [Release] 1차 배포 - Logstash 설정 추가
  build.gradle
  src/main/resources/logback.xml
Labels: 🌏 Deploy

#129 QPartyUser import 올바르게 수정
  src/main/java/wad/seoul_nolgoat/domain/party/PartyRepositoryCustomImpl.java
  src/main/java/wad/seoul_nolgoat/domain/partyuser/PartyUserRepositoryCustomImpl.java
Labels: 🐞 Fix

#133 컨벤션에 맞게 필터 클래스명 수정
  src/main/java/wad/seoul_nolgoat/config/LogFilterConfig.java
  src/main/java/wad/seoul_nolgoat/filter/MdcFilter.java
Labels: 🛠️ Refactor

#135 가게 목록 조회 성능 개선
  src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustomImpl.java
Labels: 🛠️ Refactor

#139 추가한 로직이 반영되지 않은 테스트 수정
  src/test/java/wad/seoul_nolgoat/service/PartyServiceTest.java
Labels: ✅ Test

#140 [Release] 1차 배포 - 파티 로직 및 시큐리티 설정 수정, 조회 성능 개선, 파티 DTO 스펙 수정
  .github/workflows/build-test.yml
  .github/workflows/deploy.yml
  .gitignore
  src/main/java/wad/seoul_nolgoat/auth/util/AuthUrlManager.java
  src/main/java/wad/seoul_nolgoat/config/LogFilterConfig.java
  src/main/java/wad/seoul_nolgoat/config/SecurityConfig.java
  src/main/java/wad/seoul_nolgoat/domain/comment/CommentRepositoryCustom.java
  src/main/java/wad/seoul_nolgoat/domain/comment/CommentRepositoryCustomImpl.java
  src/main/java/wad/seoul_nolgoat/domain/party/PartyRepositoryCustom.java
  src/main/java/wad/seoul_nolgoat/domain/party/PartyRepositoryCustomImpl.java
  src/main/java/wad/seoul_nolgoat/domain/partyuser/PartyUser.java
  src/main/java/wad/seoul_nolgoat/domain/partyuser/PartyUserRepository.java
  src/main/java/wad/seoul_nolgoat/domain/partyuser/PartyUserRepositoryCustom.java
  src/main/java/wad/seoul_nolgoat/domain/partyuser/PartyUserRepositoryCustomImpl.java
  src/main/java/wad/seoul_nolgoat/domain/store/StoreRepositoryCustomImpl.java
  src/main/java/wad/seoul_nolgoat/filter/MdcFilter.java
  src/main/java/wad/seoul_nolgoat/service/party/PartyService.java
  src/main/java/wad/seoul_nolgoat/util/DateTimeUtil.java
  src/main/java/wad/seoul_nolgoat/web/comment/CommentController.java
  src/main/java/wad/seoul_nolgoat/web/comment/dto/response/CommentDetailsForPartyDto.java
  src/main/java/wad/seoul_nolgoat/web/inquiry/InquiryController.java
  src/main/java/wad/seoul_nolgoat/web/notice/NoticeController.java
  src/main/java/wad/seoul_nolgoat/web/party/PartyController.java
  src/main/java/wad/seoul_nolgoat/web/party/request/PartySaveDto.java
  src/main/java/wad/seoul_nolgoat/web/party/request/PartyUpdateDto.java
  src/main/java/wad/seoul_nolgoat/web/party/response/PartyDetailsDto.java
  src/main/java/wad/seoul_nolgoat/web/party/response/PartyDetailsForListDto.java
  src/main/java/wad/seoul_nolgoat/web/party/response/PartyDetailsForUserDto.java
  src/main/java/wad/seoul_nolgoat/web/review/ReviewController.java
  src/main/resources/application.yml
  src/main/resources/logback-dev.xml
  src/main/resources/logback-prod.xml
  src/test/java/wad/seoul_nolgoat/service/PartyServiceTest.java
  src/test/resources/data.sql
Labels: 🌏 Deploy

#148 로그 서버의 탄력적 IP 주소를 설정에 반영
  src/main/resources/logback-prod.xml
Labels: ⚙ Setting

#152 System Architecture 수정
  README.md
Labels: 📃 Docs

#153 [Release] 1차 배포 - 최종
  README.md
  src/main/java/wad/seoul_nolgoat/auth/security/AuthFilter.java
  src/main/java/wad/seoul_nolgoat/auth/security/AuthUrlManager.java
  src/main/java/wad/seoul_nolgoat/config/SecurityConfig.java
  src/main/java/wad/seoul_nolgoat/domain/party/PartyRepositoryCustomImpl.java
  src/main/java/wad/seoul_nolgoat/web/party/request/PartySaveDto.java
  src/main/java/wad/seoul_nolgoat/web/party/request/PartyUpdateDto.java
  src/main/resources/logback-prod.xml
Labels: 🌏 Deploy

#156 [Release] 2차 배포
  src/main/java/wad/seoul_nolgoat/domain/comment/Comment.java
  src/main/java/wad/seoul_nolgoat/domain/comment/CommentRepositoryCustomImpl.java
  src/main/java/wad/seoul_nolgoat/service/comment/CommentService.java
  src/main/java/wad/seoul_nolgoat/web/comment/dto/response/CommentDetailsForPartyDto.java
  src/main/java/wad/seoul_nolgoat/web/comment/dto/response/CommentDetailsForUserDto.java
Labels: 🌏 Deploy
